---
- name: Initiate database
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  args:
    creates: /var/lib/pgsql/11/data/postgresql.conf

- name: Set up postgresl connection permissions
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/11/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0700



- name: Start PostgreSQL and enable at boot
  service:
    name: postgresql-11
    enabled: yes
    state: started



