---
- name: Initiate database
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  args:
    creates: /var/lib/pgsql/9.4/data/postgresql.conf

- name: Set up postgresl connection permissions
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.4/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0700



- name: Start PostgreSQL and enable at boot
  service:
    name: postgresql-9.4
    enabled: yes
    state: started



