---

- name: Disable default postgres packages
  copy:
    src: exclude-postgres.repo
    dest: /etc/yum.repos.d/exclude-default-postgres.repo
    owner: root
    group: root
    mode: 0644

- name: Install PGDG repository config RPM
  yum:
    name: "http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm"
    state: installed

- name: Install Postgresql server package
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
      - postgresql94-server
