---

- name: Disable default postgres packages
  copy:
    src: exclude-default-postgres.repo
    dest: /etc/yum.repos.d/exclude-default-postgres.repo
    owner: root
    group: root
    mode: 0644

- name: Install PGDG repository config RPM
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: installed

- name: Install Postgresql server package
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
      - postgresql94-server
      - postgresql94-contrib
