---

- name: Disable default postgres packages
  blockinfile:
    dest: "/etc/yum.repos.d/CentOS-Base.repo" 
    block: |
      [base]
      exclude=postgresql*

- name: Disable default postgres packages
  blockinfile:
    dest: "/etc/yum.repos.d/CentOS-Base.repo" 
    block: |
      [base]
      exclude=postgresql*

- name: Install PGDG repository config RPM
  yum:
    name: "http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm"
    state: installed

- name: Install Postgresql server package
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
      - postgresql94-server
